In [2]:
import pandas as pd

kp_dst_df = pd.read_csv(
    "/Users/manasstark/Desktop/PROJECTS/Space Weather Dashboard V2/data/processed/kp_dst.csv",
    parse_dates=["datetime"],
    index_col="datetime"
)

In [3]:
kp_dst_df.head()

                     kp  dst
datetime
2023-01-01 00:00:00  23  -23
2023-01-01 01:00:00  23  -21
2023-01-01 02:00:00  23  -23
2023-01-01 03:00:00  30  -26
2023-01-01 04:00:00  30  -26

In [4]:
kp_dst_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 26304 entries, 2023-01-01 00:00:00 to 2025-12-31 23:00:00
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kp      26304 non-null  int64
 1   dst     26304 non-null  int64
dtypes: int64(2)
memory usage: 616.5 KB

In [5]:
kp_dst_df.columns

Index(['kp', 'dst'], dtype='object')

In [6]:
kp_df = kp_dst_df[
    ["kp"]
].copy()

In [7]:
kp_df.head()

                     kp
datetime
2023-01-01 00:00:00  23
2023-01-01 01:00:00  23
2023-01-01 02:00:00  23
2023-01-01 03:00:00  30
2023-01-01 04:00:00  30

In [8]:
dst_df = kp_dst_df[
    ["dst"]
].copy()

In [9]:
kp_df.isna().sum()

kp    0
dtype: int64

In [10]:
dst_df.isna().sum()

dst    0
dtype: int64

In [11]:
kp_df.to_csv("/Users/manasstark/Desktop/PROJECTS/Space Weather Dashboard V2/data/processed/kp.csv")

In [12]:
dst_df.to_csv("/Users/manasstark/Desktop/PROJECTS/Space Weather Dashboard V2/data/processed/dst.csv")